Fix Pagination next prev border,Fix Breadcrumbs slash space,Fix Form validation icon position
MahdiMajidzadeh/bootstrap-v4-rtl pull request #43
Opened 2019-06-13 14:36 UTC by mortezakarimi

Fix Pagination next prev border
Fix Breadcrumbs slash space
Fix Form validation icon position

2019-06-13 23:48 UTC, MahdiMajidzadeh requested changes
thanks for translating, but is it better to make a seperate file for Persian demo and link from original demo to Persian version

2019-06-13 23:49 UTC, MahdiMajidzadeh requested changes
please remove mixin block and use them correctly

2019-06-14 08:15 UTC, mortezakarimi commented
Remove unused mixin properties
Added Persian translated version in `index-fa.html`

2019-06-14 11:51 UTC, MahdiMajidzadeh approved these changes

2019-06-14 11:53 UTC, merged